nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.7.0.cjs

packageExtensions:
  "@chromatic-com/storybook@*":
    peerDependencies:
      react: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/experimental-addon-test@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/react-vite@*":
    peerDependencies:
      typescript: "*"
  "eslint-plugin-storybook@*":
    peerDependencies:
      typescript: "*"
  "@storybook/core@*":
    peerDependencies:
      storybook: "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@types/react": "*"